Try to fix build error
In file included from /__w/zmk-config-zen-2/zmk-config-zen-2/zephyr/include/zephyr/toolchain.h:50,
                 from /__w/zmk-config-zen-2/zmk-config-zen-2/zephyr/include/zephyr/kernel_includes.h:23,
                 from /__w/zmk-config-zen-2/zmk-config-zen-2/zephyr/include/zephyr/kernel.h:17,
                 from /__w/zmk-config-zen-2/zmk-config-zen-2/zephyr/subsys/bluetooth/host/hci_core.c:10:
/__w/zmk-config-zen-2/zmk-config-zen-2/zephyr/include/zephyr/toolchain/gcc.h:87:36: error: static assertion failed: ""
   87 | #define BUILD_ASSERT(EXPR, MSG...) _Static_assert(EXPR, "" MSG)
      |                                    ^~~~~~~~~~~~~~
/__w/zmk-config-zen-2/zmk-config-zen-2/zephyr/subsys/bluetooth/host/hci_core.c:4112:1: note: in expansion of macro BUILD_ASSERT
 4112 | BUILD_ASSERT(DEVICE_NAME_LEN < CONFIG_BT_DEVICE_NAME_MAX);
      | ^~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.